/**
 * Clawforce skill topic — Config Reference
 *
 * Generates the domain-based config reference.
 */

export function generate(): string {
  const sections: string[] = [
    "# Project Configuration Reference",
    "",
    "Clawforce uses a config directory with a shared `config.yaml` plus one file per domain under `domains/*.yaml`.",
    "",
    "## Config Layout",
    "",
    "```text",
    "clawforce/",
    "  config.yaml",
    "  domains/",
    "    <domain>.yaml",
    "```",
    "",
    "`config.yaml` defines the global agent roster, shared defaults, mixins, approval policy, and reusable templates. Each `domains/<domain>.yaml` file assigns agents to a domain and adds domain-specific settings like paths, budgets, policies, and rules.",
    "",
    "## config.yaml Fields",
    "",
    "| Field | Type | Description |",
    "| --- | --- | --- |",
    "| `name` | string | Human-readable project name |",
    "| `approval` | object | Approval policy configuration |",
    "| `agents` | object | Agent configurations keyed by agent ID |",
    "| `budgets` | object | Shared budget limits |",
    "| `policies` | array | Shared policy rules |",
    "| `monitoring` | object | SLOs, anomaly detection, and alert rules |",
    "| `risk_tiers` | object | Risk classification and gate policies |",
    "| `mixins` | object | Reusable config fragments for agents |",
    "| `team_templates` | object | Team-scoped defaults |",
    "",
    "## domains/<domain>.yaml Fields",
    "",
    "| Field | Type | Description |",
    "| --- | --- | --- |",
    "| `domain` | string | Domain identifier |",
    "| `enabled` | boolean | Disable automatic loading when false |",
    "| `agents` | string[] | Agent IDs from `config.yaml` assigned to this domain |",
    "| `manager` | object | Domain manager settings such as `agentId` |",
    "| `paths` | string[] | Workspace paths claimed by the domain |",
    "| `budget` | object | Domain budget settings |",
    "| `policies` | array | Domain policy rules |",
    "| `rules` | array | Event-driven automation rules |",
    "| `operational_profile` | string | Domain operational profile |",
    "",
    "Rules use a `trigger` plus an `action` object. For prompt-driven dispatch actions, the action includes fields such as `agent` and `prompt_template`.",
    "",
    "## Approval Config",
    "",
    "```yaml",
    "approval:",
    "  policy: \"Natural language policy text for managers to follow when reviewing proposals.\"",
    "```",
    "",
    "## Agent Config Fields",
    "",
    "Each agent is defined under the `agents` key in `config.yaml`:",
    "",
    "| Field | Type | Required | Description |",
    "| --- | --- | --- | --- |",
    "| `extends` | string | yes | Preset to inherit: `manager`, `employee`, `assistant`, or custom |",
    "| `title` | string | no | Job title (e.g. \"VP of Engineering\") |",
    "| `persona` | string | no | System prompt personality |",
    "| `tools` | string[] | no | Tools this agent is allowed to use |",
    "| `channel` | string | no | Communication channel (e.g. \"telegram\", \"slack\") |",
    "| `department` | string | no | Department (e.g. \"engineering\") |",
    "| `team` | string | no | Team within department (e.g. \"frontend\") |",
    "| `reports_to` | string | no | Manager agent ID or `parent` |",
    "| `briefing` | array | no | Context sources for session startup |",
    "| `exclude_briefing` | string[] | no | Sources to exclude from preset defaults |",
    "| `expectations` | array | no | Minimum tool call requirements |",
    "| `performance_policy` | object | no | What happens on non-compliance |",
    "| `jobs` | object | no | Scheduled or triggered jobs |",
    "| `memory` | object | no | Recall and persistence configuration |",
    "| `compaction` | bool/object | no | Session compaction settings |",
    "",
    "## Complete Example",
    "",
    "```yaml",
    "# config.yaml",
    "name: My Project",
    "",
    "approval:",
    "  policy: >-",
    "    Approve well-scoped proposals with clear success criteria.",
    "    Reject proposals that are too broad or lack justification.",
    "",
    "agents:",
    "  lead:",
    "    extends: manager",
    '    title: "Engineering Lead"',
    "    department: engineering",
    "    persona: >-",
    "      You are the engineering lead. Prioritize code quality and test coverage.",
    "    briefing:",
    "      - source: team_performance",
    "",
    "  dev-1:",
    "    extends: employee",
    '    title: "Frontend Developer"',
    "    reports_to: lead",
    "    department: engineering",
    "    team: frontend",
    "    expectations:",
    "      - tool: clawforce_task",
    "        action: [transition, fail]",
    "        min_calls: 1",
    "      - tool: clawforce_log",
    "        action: write",
    "        min_calls: 1",
    "    performance_policy:",
    "      action: retry",
    "      max_retries: 3",
    "      then: alert",
    "```",
    "",
    "```yaml",
    "# domains/my-project.yaml",
    "domain: my-project",
    "paths:",
    "  - ~/projects/my-project",
    "agents:",
    "  - lead",
    "  - dev-1",
    "manager:",
    "  enabled: true",
    "  agentId: lead",
    "",
    "budget:",
    "  project:",
    "    daily_limit: 100.00",
    "  agents:",
    "    dev-1:",
    "      daily_limit: 30.00",
    "      task_limit: 10.00",
    "",
    "policies:",
    "  - name: no-ops-for-employees",
    "    type: action_scope",
    "    target: dev-1",
    "    config:",
    "      denied_tools: [clawforce_ops]",
    "```",
    "",
    "## Notes",
    "",
    "- Keep shared agent definitions in `config.yaml`.",
    "- Keep domain membership and domain-specific behavior in `domains/<domain>.yaml`.",
    "- Use `clawforce_setup validate` before activation.",
    "- Use `clawforce_setup activate` with the domain ID to reload changes live.",
  ];

  return sections.join("\n");
}
