/**
 * Clawforce skill topic — Config Reference
 *
 * Generates the full project.yaml reference.
 */

export function generate(): string {
  const sections: string[] = [
    "# Project Configuration Reference",
    "",
    "Clawforce projects are configured via a `project.yaml` file. This document covers all top-level fields and their options.",
    "",

    "## Top-Level Fields",
    "",
    "| Field | Type | Description |",
    "| --- | --- | --- |",
    "| `id` | string | Unique project identifier |",
    "| `name` | string | Human-readable project name |",
    "| `dir` | string | Project directory path (supports `~` expansion) |",
    "| `approval` | object | Approval policy configuration |",
    "| `agents` | object | Agent configurations (keyed by agent ID) |",
    "| `budgets` | object | Budget limits for project and agents |",
    "| `policies` | array | Policy rules for enforcement |",
    "| `monitoring` | object | SLOs, anomaly detection, and alert rules |",
    "| `risk_tiers` | object | Risk classification and gate policies |",
    "",

    "## Approval Config",
    "",
    "```yaml",
    "approval:",
    "  policy: \"Natural language policy text for managers to follow when reviewing proposals.\"",
    "```",
    "",

    "## Agent Config Fields",
    "",
    "Each agent is defined under the `agents` key:",
    "",
    "| Field | Type | Required | Description |",
    "| --- | --- | --- | --- |",
    "| `extends` | string | no | Preset to inherit: `manager`, `employee`, `assistant`, or custom (defaults to `employee`) |",
    "| `title` | string | no | Job title (e.g. \"VP of Engineering\") |",
    "| `model` | string | no | AI model to use (e.g. \"claude-opus-4-6\") |",
    "| `provider` | string | no | Model provider (e.g. \"anthropic\") |",
    "| `persona` | string | no | System prompt personality |",
    "| `tools` | string[] | no | Tools this agent is allowed to use |",
    "| `permissions` | object | no | Agent permissions (can_hire, can_fire, budget_limit_cents) |",
    "| `channel` | string | no | Communication channel (e.g. \"telegram\", \"slack\") |",
    "| `department` | string | no | Department (e.g. \"engineering\") |",
    "| `team` | string | no | Team within department (e.g. \"frontend\") |",
    "| `reports_to` | string | no | Manager agent ID or \"parent\" |",
    "| `briefing` | array | no | Context sources for session startup |",
    "| `exclude_briefing` | string[] | no | Sources to exclude from role defaults |",
    "| `expectations` | array | no | Minimum tool call requirements |",
    "| `performance_policy` | object | no | What happens on non-compliance |",
    "| `compaction` | bool/object | no | Session compaction settings |",
    "",

    "## Budget Config",
    "",
    "```yaml",
    "budgets:",
    "  project:",
    "    daily_limit: 50.00     # dollars per day",
    "    session_limit: 10.00   # dollars per session",
    "    task_limit: 5.00       # dollars per task",
    "  agents:",
    "    <agent-id>:",
    "      daily_limit: 20.00",
    "      task_limit: 5.00",
    "```",
    "",

    "## Policy Config",
    "",
    "```yaml",
    "policies:",
    "  - name: policy-name",
    "    type: action_scope | transition_gate | spend_limit | approval_required",
    "    target: agent-id        # optional, applies to all if omitted",
    "    config:",
    "      # type-specific fields",
    "```",
    "",

    "## Monitoring Config",
    "",
    "```yaml",
    "monitoring:",
    "  slos:",
    "    <slo-name>:",
    "      metricType: string",
    "      metricKey: string",
    "      aggregation: avg | sum | count | min | max",
    "      condition: lt | gt | lte | gte",
    "      threshold: number",
    "      windowMs: number",
    "      severity: warning | critical",
    "      onBreach:",
    "        action: create_task",
    "        taskTitle: string",
    "        taskPriority: P0-P3",
    "",
    "  anomaly_detection:",
    "    <anomaly-name>:",
    "      metricType: string",
    "      metricKey: string",
    "      lookbackWindows: number",
    "      windowMs: number",
    "      stddevThreshold: number",
    "",
    "  alert_rules:",
    "    <rule-name>:",
    "      metricType: string",
    "      metricKey: string",
    "      condition: gt | lt | gte | lte | eq",
    "      threshold: number",
    "      windowMs: number",
    "      action: create_task | emit_event | escalate",
    "      cooldownMs: number",
    "```",
    "",

    "## Risk Tiers Config",
    "",
    "```yaml",
    "risk_tiers:",
    "  enabled: true",
    "  default_tier: low",
    "  policies:",
    "    low:      { gate: none }",
    "    medium:   { gate: delay, delay_ms: 30000 }",
    "    high:     { gate: approval }",
    "    critical: { gate: human_approval }",
    "  patterns:",
    "    - match: { tool_name: clawforce_ops, tool_action: kill_agent }",
    "      tier: critical",
    "```",
    "",

    "## Complete Example",
    "",
    "```yaml",
    "id: my-project",
    "name: My Project",
    "dir: ~/projects/my-project",
    "",
    "approval:",
    "  policy: >-",
    "    Approve well-scoped proposals with clear success criteria.",
    "    Reject proposals that are too broad or lack justification.",
    "",
    "agents:",
    "  lead:",
    "    extends: manager",
    '    title: "Engineering Lead"',
    "    department: engineering",
    "    persona: >-",
    "      You are the engineering lead. Prioritize code quality and test coverage.",
    "    briefing:",
    "      - source: team_performance",
    "",
    "  dev-1:",
    "    extends: employee",
    '    title: "Frontend Developer"',
    "    reports_to: lead",
    "    department: engineering",
    "    team: frontend",
    "    model: claude-sonnet-4-20250514",
    "    expectations:",
    "      - tool: clawforce_task",
    "        action: [transition, fail]",
    "        min_calls: 1",
    "      - tool: clawforce_log",
    "        action: write",
    "        min_calls: 1",
    "    performance_policy:",
    "      action: retry",
    "      max_retries: 3",
    "      then: alert",
    "",
    "  nightly-check:",
    "    extends: employee",
    '    title: "Nightly Health Check"',
    "    reports_to: lead",
    "    department: engineering",
    "",
    "budgets:",
    "  project:",
    "    daily_limit: 100.00",
    "  agents:",
    "    dev-1:",
    "      daily_limit: 30.00",
    "      task_limit: 10.00",
    "",
    "policies:",
    "  - name: no-ops-for-employees",
    "    type: action_scope",
    "    target: dev-1",
    "    config:",
    "      denied_tools: [clawforce_ops]",
    "",
    "monitoring:",
    "  slos:",
    "    task-completion-rate:",
    "      metricType: task",
    "      metricKey: completion_rate",
    "      aggregation: avg",
    "      condition: gte",
    "      threshold: 0.8",
    "      windowMs: 86400000",
    "      severity: warning",
    "",
    "risk_tiers:",
    "  enabled: true",
    "  default_tier: low",
    "  policies:",
    "    low: { gate: none }",
    "    medium: { gate: delay, delay_ms: 30000 }",
    "    high: { gate: approval }",
    "    critical: { gate: human_approval }",
    "  patterns:",
    "    - match: { tool_action: kill_agent }",
    "      tier: critical",
    "    - match: { to_state: CANCELLED }",
    "      tier: high",
    "```",
    "",

    "## Domain Configuration",
    "",
    "Clawforce uses a two-tier config system:",
    "",
    "- **Global config** (`~/.clawforce/config.yaml`): Agent roster and defaults",
    "- **Domain configs** (`~/.clawforce/domains/<name>.yaml`): Per-domain settings",
    "",
    "### Global Config Structure",
    "```yaml",
    "defaults:",
    "  model: anthropic/claude-opus-4-6",
    "agents:",
    "  my-agent:",
    "    extends: employee",
    "```",
    "",
    "### Domain Config Structure",
    "```yaml",
    "domain: my-domain",
    "orchestrator: lead-agent",
    "paths:",
    "  - ~/code/my-project",
    "agents:",
    "  - my-agent",
    "budget:",
    "  daily: $5.00",
    "rules:",
    "  - name: deploy-review",
    "    trigger:",
    "      event: task.completed",
    "      match: { tags: [deploy] }",
    "    action:",
    "      agent: reviewer",
    '      prompt_template: "Review deployment for {{task.title}}"',
    "```",
    "",
    "## Rule System",
    "",
    "Rules are pre-built prompt templates with trigger conditions. They automate recurring decisions without LLM cost:",
    "",
    "- **trigger.event**: The event type to match (e.g., task.completed, session.ended)",
    "- **trigger.match**: Optional criteria to filter (e.g., specific tags)",
    "- **action.agent**: Which agent to dispatch",
    "- **action.prompt_template**: Template with {{variable}} interpolation",
    "",
    "Rules evolve from analytical decisions — when orchestrators notice repeated judgment calls, they flag them as rule candidates for codification.",
    "",
  ];

  return sections.join("\n");
}
