/**
 * Clawforce skill topic — Context Sources
 *
 * Documents all ContextSource types available for agent briefing.
 */

export function generate(): string {
  // These source types come from the ContextSource type definition in types.ts:
  // "instructions" | "custom" | "project_md" | "task_board" | "assigned_task" |
  // "knowledge" | "file" | "skill" | "memory" | "escalations" | "workflows" |
  // "activity" | "sweep_status" | "proposals" | "agent_status" | "cost_summary" |
  // "policy_status" | "health_status" | "team_status" | "team_performance" |
  // "soul" | "tools_reference"
  const sources: Array<{ name: string; description: string; extra?: string }> = [
    { name: "instructions", description: "System instructions for the agent role. Always auto-injected regardless of profile." },
    { name: "custom", description: "Raw markdown content specified inline.", extra: "`content` (string) — the markdown text to inject" },
    { name: "project_md", description: "The project's PROJECT.md charter file." },
    { name: "task_board", description: "Current task board state — all tasks with statuses, priorities, and assignees." },
    { name: "assigned_task", description: "The specific task assigned to this agent (for employees)." },
    { name: "knowledge", description: "Knowledge base entries filtered by category or tags.", extra: "`filter` — `{ category?: string[], tags?: string[] }`" },
    { name: "file", description: "Contents of a specific file on disk.", extra: "`path` (string) — relative or absolute file path" },
    { name: "skill", description: "Skill topic documentation (generated by the skill system)." },
    { name: "memory", description: "Shared memories from previous sessions and same-type agents, auto-filtered by agent scopes." },
    { name: "escalations", description: "Pending escalation messages from direct reports." },
    { name: "workflows", description: "Active workflow status — phases, gates, and progress." },
    { name: "activity", description: "Recent activity log entries across the project." },
    { name: "sweep_status", description: "Latest sweep results — findings and recommendations." },
    { name: "proposals", description: "Pending proposals awaiting approval." },
    { name: "agent_status", description: "Status of all agents — active, disabled, compliance state." },
    { name: "cost_summary", description: "Budget usage and cost breakdown across agents and tasks." },
    { name: "policy_status", description: "Active policies and recent violations." },
    { name: "health_status", description: "System health — SLO status, anomalies, alerts." },
    { name: "team_status", description: "Status of agents in the manager's team/department." },
    { name: "team_performance", description: "Performance metrics for the manager's team." },
    { name: "soul", description: "Agent's SOUL.md identity document. Overrides config.persona when present on disk at `agents/{id}/SOUL.md`." },
    { name: "tools_reference", description: "Scoped tools reference for the agent. Auto-generated from effective action scope; can be overridden with `agents/{id}/TOOLS.md`." },
    { name: "goal_hierarchy", description: "Active goal hierarchy with progress tracking and cascade status." },
  ];

  const sections: string[] = [
    "# Context Sources",
    "",
    "Context sources define what information is injected into an agent's session at startup. Each source is specified in the `briefing` array of the agent config.",
    "",
    "The `instructions` source is always auto-injected regardless of profile or config.",
    "",
    "## Source Reference",
    "",
    "| Source | Description | Extra Fields |",
    "| --- | --- | --- |",
  ];

  for (const source of sources) {
    const extra = source.extra ?? "—";
    sections.push(`| \`${source.name}\` | ${source.description} | ${extra} |`);
  }

  sections.push("");
  sections.push("## Usage in Config");
  sections.push("");
  sections.push("```yaml");
  sections.push("agents:");
  sections.push("  my-agent:");
  sections.push("    role: employee");
  sections.push("    briefing:");
  sections.push("      - source: assigned_task");
  sections.push("      - source: knowledge");
  sections.push("        filter:");
  sections.push("          category: [decision, pattern]");
  sections.push("      - source: file");
  sections.push("        path: ./docs/guidelines.md");
  sections.push("      - source: custom");
  sections.push('        content: "Always run tests before submitting."');
  sections.push("      - source: memory");
  sections.push("```");
  sections.push("");
  sections.push("## Excluding Default Sources");
  sections.push("");
  sections.push("Use `exclude_briefing` to remove sources from the role's default profile:");
  sections.push("");
  sections.push("```yaml");
  sections.push("agents:");
  sections.push("  my-manager:");
  sections.push("    role: manager");
  sections.push("    exclude_briefing:");
  sections.push("      - sweep_status");
  sections.push("      - cost_summary");
  sections.push("```");
  sections.push("");

  return sections.join("\n");
}
