/**
 * Clawforce skill topic — Org Structure
 *
 * Documents organization hierarchy, escalation chains, and department/team scoping.
 */

export function generate(): string {
  const sections: string[] = [
    "# Organization Structure",
    "",
    "Clawforce supports hierarchical organization of agents through reporting chains, departments, and teams.",
    "",

    "## Reporting Chain (`reports_to`)",
    "",
    "Each agent can specify a `reports_to` field in its config:",
    "",
    "- **`\"parent\"`** (default): Relies on subagent auto-announce to the parent session. Escalations go to the spawning agent.",
    "- **`\"<agentName>\"`**: Escalation messages are injected into the named agent's session.",
    "",
    "```yaml",
    "agents:",
    "  lead-dev:",
    "    extends: manager",
    "    department: engineering",
    "",
    "  dev-1:",
    "    extends: employee",
    "    reports_to: lead-dev",
    "    department: engineering",
    "    team: frontend",
    "",
    "  dev-2:",
    "    extends: employee",
    "    reports_to: lead-dev",
    "    department: engineering",
    "    team: backend",
    "```",
    "",

    "## Escalation Chains",
    "",
    "The system resolves the full escalation chain from any agent up to the root:",
    "",
    "1. Start at the agent",
    "2. Follow `reports_to` to the immediate manager",
    "3. Follow that manager's `reports_to` to their manager",
    "4. Continue until reaching an agent with `reports_to: parent` or no `reports_to`",
    "",
    "Cycle detection is built in — if a cycle is found, the chain stops and a diagnostic event is emitted.",
    "",
    "When a performance policy triggers an alert (e.g. after retries exhausted), the escalation is routed up this chain.",
    "",

    "## Departments",
    "",
    "The `department` field groups agents by organizational unit (e.g. `engineering`, `sales`, `marketing`).",
    "",
    "Departments affect:",
    "",
    "- **Task scoping**: Managers can view tasks filtered by their department",
    "- **Memory scoping**: Memories saved with scope `dept:<name>` are shared across the department",
    "- **Team status**: The `team_status` context source shows agents in the manager's department",
    "",

    "## Teams",
    "",
    "The `team` field provides finer-grained grouping within a department (e.g. `frontend`, `backend`, `lead-gen`).",
    "",
    "Teams affect:",
    "",
    "- **Memory scoping**: Memories saved with scope `team:<name>` are shared across the team",
    "- **Agent discovery**: The system can list all agents in a given team",
    "",

    "## Escalation Routing",
    "",
    "When an agent's performance policy triggers an escalation:",
    "",
    "1. The system resolves the agent's escalation chain",
    "2. The first agent in the chain receives the escalation message",
    "3. The message appears in the manager's `escalations` context source",
    "4. The manager can then take action (reassign, create new tasks, etc.)",
    "",
    "If `reports_to` is `parent` or unset, the escalation goes through the subagent auto-announce mechanism (default Claude behavior).",
    "",

    "## Task Board Scoping for Managers",
    "",
    "When a manager has a `department` or `team` set, the `task_board` context source automatically filters to show:",
    "",
    "- Tasks assigned to agents in their department/team",
    "- Unassigned tasks in their department/team",
    "- Tasks they created",
    "",
    "This keeps the manager focused on their area of responsibility.",
    "",
  ];

  return sections.join("\n");
}
