export const CONTEXT_SOURCE_NAMES = [
  "instructions",
  "custom",
  "project_md",
  "task_board",
  "assigned_task",
  "knowledge",
  "file",
  "skill",
  "memory",
  "memory_instructions",
  "memory_review_context",
  "escalations",
  "workflows",
  "activity",
  "sweep_status",
  "proposals",
  "agent_status",
  "cost_summary",
  "policy_status",
  "health_status",
  "team_status",
  "team_performance",
  "soul",
  "tools_reference",
  "pending_messages",
  "user_messages",
  "goal_hierarchy",
  "channel_messages",
  "planning_delta",
  "velocity",
  "preferences",
  "trust_scores",
  "resources",
  "entity_registry",
  "initiative_status",
  "cost_forecast",
  "available_capacity",
  "knowledge_candidates",
  "budget_guidance",
  "onboarding_welcome",
  "weekly_digest",
  "intervention_suggestions",
  "custom_stream",
  "observed_events",
  "direction",
  "policies",
  "standards",
  "architecture",
  "task_creation_standards",
  "execution_standards",
  "review_standards",
  "rejection_standards",
  "worker_findings",
  "recent_decisions",
  "clawforce_health_report",
  "budget_plan",
] as const;

export type ContextSourceName = typeof CONTEXT_SOURCE_NAMES[number];

export const CONTEXT_SOURCE_NAME_SET = new Set<string>(CONTEXT_SOURCE_NAMES);

export function isKnownContextSource(value: string): value is ContextSourceName {
  return CONTEXT_SOURCE_NAME_SET.has(value);
}

export const CONTEXT_SOURCE_PRIORITIES: Partial<Record<ContextSourceName, number>> = {
  instructions: 1,
  soul: 1,
  direction: 1,
  policies: 1,
  standards: 1,
  custom: 1,
  project_md: 1,
  memory_instructions: 1,
  onboarding_welcome: 1,
  architecture: 1,

  task_board: 2,
  assigned_task: 2,
  task_creation_standards: 2,
  execution_standards: 2,
  review_standards: 2,
  rejection_standards: 2,

  escalations: 3,
  pending_messages: 3,
  user_messages: 3,
  proposals: 3,
  channel_messages: 3,
  worker_findings: 3,
  intervention_suggestions: 3,

  planning_delta: 4,
  goal_hierarchy: 4,
  initiative_status: 4,
  workflows: 4,
  recent_decisions: 4,
  budget_plan: 4,
  budget_guidance: 4,

  team_status: 5,
  team_performance: 5,
  agent_status: 5,
  trust_scores: 5,
  velocity: 5,
  cost_summary: 5,
  cost_forecast: 5,
  available_capacity: 5,

  health_status: 6,
  sweep_status: 6,
  activity: 6,
  observed_events: 6,
  clawforce_health_report: 6,
  weekly_digest: 6,
  policy_status: 6,
  knowledge: 6,
  knowledge_candidates: 6,
  memory_review_context: 6,
  preferences: 6,
  resources: 6,
  entity_registry: 6,
  skill: 6,
  tools_reference: 6,
  file: 6,
  custom_stream: 6,
};

export const DEFAULT_CONTEXT_SOURCE_PRIORITY = 4;

export const STATIC_CONTEXT_SOURCES = new Set<ContextSourceName>([
  "soul",
  "project_md",
  "skill",
  "tools_reference",
  "memory_instructions",
  "instructions",
]);
